apiVersion: apps/v1
kind: Deployment
metadata:
  name: door2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: door2
  template:
    metadata:
      labels:
        app: door2
    spec:
      containers:
        - name: door1
          args: ["2", "10", "redis-service:6379"]
          image: eu.gcr.io/ecstatic-device-271610/door:v1
